version: '3.8'

volumes:
  pg_app:

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/data_json
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 6145761457

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: data_json
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6145761457
    ports:
      - "5432:5432"
